[package]
name = "qasm2-parse"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
float-cmp = "0.10.0"
itertools = "0.14.0"
logos = "0.15.1"
rustc-hash = "2.1.1"
self_cell = "1.2.1"
thiserror = "2.0.17"
